### ISSUE TITLE
Bunch of errors compiling

### ISSUE THREAD

**Issue by topnepu** [kmatheussen/radium#1339] opened 2021-03-18 16:40 UTC
slackware64-current, i'm now getting this when compiling packages. compiling the latest version.

> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_code_container.cpp: In member function ‘void LLVMCodeContainer::init(const string&, int, int, llvm::Module*, llvm::LLVMContext*)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_code_container.cpp:83:9: error: ‘class llvm::FastMathFlags’ has no member named ‘setUnsafeAlgebra’
>    83 |     FMF.setUnsafeAlgebra();
>       |         ^~~~~~~~~~~~~~~~
> In file included from /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/JSONUIDecoder.h:35,
>                  from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dsp_aux.cpp:42:
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h: In function ‘void buildUIGlue(UIGlue*, UI*, bool)’:
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:284:35: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addVerticalSliderFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   284 |         glue->addVerticalSlider = reinterpret_cast<addVerticalSliderFun>(addVerticalSliderGlueDouble);
>       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:285:37: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addHorizontalSliderFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   285 |         glue->addHorizontalSlider = reinterpret_cast<addHorizontalSliderFun>(addHorizontalSliderGlueDouble);
>       |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:286:29: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addNumEntryFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   286 |         glue->addNumEntry = reinterpret_cast<addNumEntryFun>(addNumEntryGlueDouble);
>       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:287:39: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double)’ to ‘addHorizontalBargraphFun’ {aka ‘void (*)(void*, const char*, float*, float, float)’} [-Wcast-function-type]
>   287 |         glue->addHorizontalBargraph = reinterpret_cast<addHorizontalBargraphFun>(addHorizontalBargraphGlueDouble);
>       |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:288:37: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double)’ to ‘addVerticalBargraphFun’ {aka ‘void (*)(void*, const char*, float*, float, float)’} [-Wcast-function-type]
>   288 |         glue->addVerticalBargraph = reinterpret_cast<addVerticalBargraphFun>(addVerticalBargraphGlueDouble);
>       |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> gmake[5]: *** [CMakeFiles/staticlib.dir/build.make:1603: CMakeFiles/staticlib.dir/home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_code_container.cpp.o] Error 1
> gmake[5]: *** Waiting for unfinished jobs....
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘virtual void llvm_dynamic_dsp_factory_aux::write(std::ostream*, bool, bool)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:120:28: error: invalid initialization of reference of type ‘const llvm::Module&’ from expression of type ‘llvm::Module*’
>   120 |         WriteBitcodeToFile(fModule, out_str);
>       |                            ^~~~~~~
> In file included from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:66:
> /usr/include/llvm/Bitcode/BitcodeWriter.h:129:41: note: in passing argument 1 of ‘void llvm::WriteBitcodeToFile(const llvm::Module&, llvm::raw_ostream&, bool, const llvm::ModuleSummaryIndex*, bool, llvm::ModuleHash*)’
>   129 |   void WriteBitcodeToFile(const Module &M, raw_ostream &Out,
>       |                           ~~~~~~~~~~~~~~^
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘virtual std::string llvm_dynamic_dsp_factory_aux::writeDSPFactoryToBitcode()’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:136:24: error: invalid initialization of reference of type ‘const llvm::Module&’ from expression of type ‘llvm::Module*’
>   136 |     WriteBitcodeToFile(fModule, out);
>       |                        ^~~~~~~
> In file included from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:66:
> /usr/include/llvm/Bitcode/BitcodeWriter.h:129:41: note: in passing argument 1 of ‘void llvm::WriteBitcodeToFile(const llvm::Module&, llvm::raw_ostream&, bool, const llvm::ModuleSummaryIndex*, bool, llvm::ModuleHash*)’
>   129 |   void WriteBitcodeToFile(const Module &M, raw_ostream &Out,
>       |                           ~~~~~~~~~~~~~~^
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘virtual bool llvm_dynamic_dsp_factory_aux::writeDSPFactoryToBitcodeFile(const string&)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:153:24: error: invalid initialization of reference of type ‘const llvm::Module&’ from expression of type ‘llvm::Module*’
>   153 |     WriteBitcodeToFile(fModule, out);
>       |                        ^~~~~~~
> In file included from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:66:
> /usr/include/llvm/Bitcode/BitcodeWriter.h:129:41: note: in passing argument 1 of ‘void llvm::WriteBitcodeToFile(const llvm::Module&, llvm::raw_ostream&, bool, const llvm::ModuleSummaryIndex*, bool, llvm::ModuleHash*)’
>   129 |   void WriteBitcodeToFile(const Module &M, raw_ostream &Out,
>       |                           ~~~~~~~~~~~~~~^
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘virtual bool llvm_dynamic_dsp_factory_aux::initJIT(std::string&)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:250:5: error: ‘initializeCodeGen’ was not declared in this scope
>   250 |     initializeCodeGen(Registry);
>       |     ^~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:251:5: error: ‘initializeCore’ was not declared in this scope
>   251 |     initializeCore(Registry);
>       |     ^~~~~~~~~~~~~~
> compilation terminated due to -fmax-errors=5.
> gmake[5]: *** [CMakeFiles/staticlib.dir/build.make:1629: CMakeFiles/staticlib.dir/home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp.o] Error 1
> gmake[5]: Leaving directory '/home/s/radium/bin/packages/faust/build/faustdir'
> gmake[4]: *** [CMakeFiles/Makefile2:180: CMakeFiles/staticlib.dir/all] Error 2
> gmake[4]: Leaving directory '/home/s/radium/bin/packages/faust/build/faustdir'
> gmake[3]: *** [Makefile:171: all] Error 2
> gmake[3]: Leaving directory '/home/s/radium/bin/packages/faust/build/faustdir'
> make[2]: *** [Makefile:80: all] Error 2
> make[2]: Leaving directory '/home/s/radium/bin/packages/faust/build'
> make[1]: *** [Makefile:33: most] Error 2
> make[1]: Leaving directory '/home/s/radium/bin/packages/faust'
> make: *** [Makefile:800: bin/packages/deletemetorebuild] Error 2

If I increase -fmax-errors I make it up to here:

> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_code_container.cpp: In member function ‘void LLVMCodeContainer::init(const string&, int, int, llvm::Module*, llvm::LLVMContext*)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_code_container.cpp:83:9: error: ‘class llvm::FastMathFlags’ has no member named ‘setUnsafeAlgebra’
>    83 |     FMF.setUnsafeAlgebra();
>       |         ^~~~~~~~~~~~~~~~
> [ 98%] Building CXX object CMakeFiles/staticlib.dir/home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp.o
> /usr/bin/g++ -DCPP_BUILD -DFAUST_SELF_CONTAINED_LIB -DINTERP_BUILD -DLIBDIR=\"lib\" -DLLVM_111 -DLLVM_BUILD -DLLVM_VERSION=\"11.1.0\" -I/home/s/radium/bin/packages/faust/compiler -I/home/s/radium/bin/packages/faust/compiler/boxes -I/home/s/radium/bin/packages/faust/compiler/documentator -I/home/s/radium/bin/packages/faust/compiler/draw -I/home/s/radium/bin/packages/faust/compiler/errors -I/home/s/radium/bin/packages/faust/compiler/evaluate -I/home/s/radium/bin/packages/faust/compiler/extended -I/home/s/radium/bin/packages/faust/compiler/generator -I/home/s/radium/bin/packages/faust/compiler/generator/fir -I/home/s/radium/bin/packages/faust/compiler/generator/interpreter -I/home/s/radium/bin/packages/faust/compiler/generator/rust -I/home/s/radium/bin/packages/faust/compiler/generator/soul -I/home/s/radium/bin/packages/faust/compiler/generator/dlang -I/home/s/radium/bin/packages/faust/compiler/normalize -I/home/s/radium/bin/packages/faust/compiler/parallelize -I/home/s/radium/bin/packages/faust/compiler/parser -I/home/s/radium/bin/packages/faust/compiler/patternmatcher -I/home/s/radium/bin/packages/faust/compiler/propagate -I/home/s/radium/bin/packages/faust/compiler/signals -I/home/s/radium/bin/packages/faust/compiler/tlib -I/home/s/radium/bin/packages/faust/compiler/transform -I/home/s/radium/bin/packages/faust/compiler/utils -I/home/s/radium/bin/packages/faust/compiler/draw/device -I/home/s/radium/bin/packages/faust/compiler/draw/schema -I/home/s/radium/bin/packages/faust/compiler/../architecture -I/home/s/radium/bin/packages/faust/compiler/generator/cpp -I/home/s/radium/bin/packages/faust/compiler/generator/llvm -I/home/s/radium/bin/packages/faust/compiler/generator/c -fmax-errors=100 -O3 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -Wno-overloaded-virtual -fPIC -DFAUST_LIB -std=gnu++14 -fno-rtti  -o CMakeFiles/staticlib.dir/home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp.o -c /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp
> In file included from /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/JSONUIDecoder.h:35,
>                  from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dsp_aux.hh:32,
>                  from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.hh:25,
>                  from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:35:
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h: In function ‘void buildUIGlue(UIGlue*, UI*, bool)’:
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:284:35: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addVerticalSliderFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   284 |         glue->addVerticalSlider = reinterpret_cast<addVerticalSliderFun>(addVerticalSliderGlueDouble);
>       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:285:37: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addHorizontalSliderFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   285 |         glue->addHorizontalSlider = reinterpret_cast<addHorizontalSliderFun>(addHorizontalSliderGlueDouble);
>       |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:286:29: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addNumEntryFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   286 |         glue->addNumEntry = reinterpret_cast<addNumEntryFun>(addNumEntryGlueDouble);
>       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:287:39: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double)’ to ‘addHorizontalBargraphFun’ {aka ‘void (*)(void*, const char*, float*, float, float)’} [-Wcast-function-type]
>   287 |         glue->addHorizontalBargraph = reinterpret_cast<addHorizontalBargraphFun>(addHorizontalBargraphGlueDouble);
>       |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:288:37: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double)’ to ‘addVerticalBargraphFun’ {aka ‘void (*)(void*, const char*, float*, float, float)’} [-Wcast-function-type]
>   288 |         glue->addVerticalBargraph = reinterpret_cast<addVerticalBargraphFun>(addVerticalBargraphGlueDouble);
>       |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> gmake[5]: *** [CMakeFiles/staticlib.dir/build.make:1603: CMakeFiles/staticlib.dir/home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_code_container.cpp.o] Error 1
> gmake[5]: *** Waiting for unfinished jobs....
> In file included from /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/JSONUIDecoder.h:35,
>                  from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dsp_aux.cpp:42:
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h: In function ‘void buildUIGlue(UIGlue*, UI*, bool)’:
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:284:35: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addVerticalSliderFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   284 |         glue->addVerticalSlider = reinterpret_cast<addVerticalSliderFun>(addVerticalSliderGlueDouble);
>       |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:285:37: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addHorizontalSliderFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   285 |         glue->addHorizontalSlider = reinterpret_cast<addHorizontalSliderFun>(addHorizontalSliderGlueDouble);
>       |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:286:29: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double, double, double)’ to ‘addNumEntryFun’ {aka ‘void (*)(void*, const char*, float*, float, float, float, float)’} [-Wcast-function-type]
>   286 |         glue->addNumEntry = reinterpret_cast<addNumEntryFun>(addNumEntryGlueDouble);
>       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:287:39: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double)’ to ‘addHorizontalBargraphFun’ {aka ‘void (*)(void*, const char*, float*, float, float)’} [-Wcast-function-type]
>   287 |         glue->addHorizontalBargraph = reinterpret_cast<addHorizontalBargraphFun>(addHorizontalBargraphGlueDouble);
>       |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/../architecture/faust/gui/CGlue.h:288:37: warning: cast between incompatible function types from ‘void (*)(void*, const char*, double*, double, double)’ to ‘addVerticalBargraphFun’ {aka ‘void (*)(void*, const char*, float*, float, float)’} [-Wcast-function-type]
>   288 |         glue->addVerticalBargraph = reinterpret_cast<addVerticalBargraphFun>(addVerticalBargraphGlueDouble);
>       |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘virtual void llvm_dynamic_dsp_factory_aux::write(std::ostream*, bool, bool)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:120:28: error: invalid initialization of reference of type ‘const llvm::Module&’ from expression of type ‘llvm::Module*’
>   120 |         WriteBitcodeToFile(fModule, out_str);
>       |                            ^~~~~~~
> In file included from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:66:
> /usr/include/llvm/Bitcode/BitcodeWriter.h:129:41: note: in passing argument 1 of ‘void llvm::WriteBitcodeToFile(const llvm::Module&, llvm::raw_ostream&, bool, const llvm::ModuleSummaryIndex*, bool, llvm::ModuleHash*)’
>   129 |   void WriteBitcodeToFile(const Module &M, raw_ostream &Out,
>       |                           ~~~~~~~~~~~~~~^
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘virtual std::string llvm_dynamic_dsp_factory_aux::writeDSPFactoryToBitcode()’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:136:24: error: invalid initialization of reference of type ‘const llvm::Module&’ from expression of type ‘llvm::Module*’
>   136 |     WriteBitcodeToFile(fModule, out);
>       |                        ^~~~~~~
> In file included from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:66:
> /usr/include/llvm/Bitcode/BitcodeWriter.h:129:41: note: in passing argument 1 of ‘void llvm::WriteBitcodeToFile(const llvm::Module&, llvm::raw_ostream&, bool, const llvm::ModuleSummaryIndex*, bool, llvm::ModuleHash*)’
>   129 |   void WriteBitcodeToFile(const Module &M, raw_ostream &Out,
>       |                           ~~~~~~~~~~~~~~^
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘virtual bool llvm_dynamic_dsp_factory_aux::writeDSPFactoryToBitcodeFile(const string&)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:153:24: error: invalid initialization of reference of type ‘const llvm::Module&’ from expression of type ‘llvm::Module*’
>   153 |     WriteBitcodeToFile(fModule, out);
>       |                        ^~~~~~~
> In file included from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:66:
> /usr/include/llvm/Bitcode/BitcodeWriter.h:129:41: note: in passing argument 1 of ‘void llvm::WriteBitcodeToFile(const llvm::Module&, llvm::raw_ostream&, bool, const llvm::ModuleSummaryIndex*, bool, llvm::ModuleHash*)’
>   129 |   void WriteBitcodeToFile(const Module &M, raw_ostream &Out,
>       |                           ~~~~~~~~~~~~~~^
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘virtual bool llvm_dynamic_dsp_factory_aux::initJIT(std::string&)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:250:5: error: ‘initializeCodeGen’ was not declared in this scope
>   250 |     initializeCodeGen(Registry);
>       |     ^~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:251:5: error: ‘initializeCore’ was not declared in this scope
>   251 |     initializeCore(Registry);
>       |     ^~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:252:5: error: ‘initializeScalarOpts’ was not declared in this scope
>   252 |     initializeScalarOpts(Registry);
>       |     ^~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:253:5: error: ‘initializeObjCARCOpts’ was not declared in this scope
>   253 |     initializeObjCARCOpts(Registry);
>       |     ^~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:254:5: error: ‘initializeVectorization’ was not declared in this scope
>   254 |     initializeVectorization(Registry);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:255:5: error: ‘initializeIPO’ was not declared in this scope
>   255 |     initializeIPO(Registry);
>       |     ^~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:256:5: error: ‘initializeAnalysis’ was not declared in this scope
>   256 |     initializeAnalysis(Registry);
>       |     ^~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:257:5: error: ‘initializeTransformUtils’ was not declared in this scope
>   257 |     initializeTransformUtils(Registry);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:258:5: error: ‘initializeInstCombine’ was not declared in this scope
>   258 |     initializeInstCombine(Registry);
>       |     ^~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:259:5: error: ‘initializeInstrumentation’ was not declared in this scope
>   259 |     initializeInstrumentation(Registry);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:260:5: error: ‘initializeTarget’ was not declared in this scope
>   260 |     initializeTarget(Registry);
>       |     ^~~~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:295:19: error: ‘llvm::DenormalMode llvm::TargetOptions::FPDenormalMode’ is private within this context
>   295 |     targetOptions.FPDenormalMode = FPDenormal::IEEE;
>       |                   ^~~~~~~~~~~~~~
> In file included from /usr/include/llvm/Target/TargetMachine.h:21,
>                  from /usr/include/llvm/ExecutionEngine/ExecutionEngine.h:32,
>                  from /usr/include/llvm/ExecutionEngine/MCJIT.h:17,
>                  from /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:39:
> /usr/include/llvm/Target/TargetOptions.h:338:18: note: declared private here
>   338 |     DenormalMode FPDenormalMode;
>       |                  ^~~~~~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:295:36: error: ‘FPDenormal’ has not been declared
>   295 |     targetOptions.FPDenormalMode = FPDenormal::IEEE;
>       |                                get    ^~~~~~~~~~
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp: In member function ‘bool llvm_dynamic_dsp_factory_aux::writeDSPFactoryToObjectcodeFileAux(const string&)’:
> /home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp:442:74: error: ‘CGFT_ObjectFile’ is not a member of ‘llvm::TargetMachine’
>   442 |     if (TheTargetMachine->addPassesToEmitFile(pass, dest, TargetMachine::CGFT_ObjectFile, true)) {
>       |                                                                          ^~~~~~~~~~~~~~~
> gmake[5]: *** [CMakeFiles/staticlib.dir/build.make:1629: CMakeFiles/staticlib.dir/home/s/radium/bin/packages/faust/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp.o] Error 1
> gmake[5]: Leaving directory '/home/s/radium/bin/packages/faust/build/faustdir'
> gmake[4]: *** [CMakeFiles/Makefile2:180: CMakeFiles/staticlib.dir/all] Error 2
> gmake[4]: Leaving directory '/home/s/radium/bin/packages/faust/build/faustdir'
> gmake[3]: *** [Makefile:171: all] Error 2
> gmake[3]: Leaving directory '/home/s/radium/bin/packages/faust/build/faustdir'
> make[2]: *** [Makefile:80: all] Error 2
> make[2]: Leaving directory '/home/s/radium/bin/packages/faust/build'
> make[1]: *** [Makefile:33: most] Error 2
> make[1]: Leaving directory '/home/s/radium/bin/packages/faust'
> make: *** [Makefile:800: bin/packages/deletemetorebuild] Error 2

**Comment by kmatheussen** [comment] 2021-04-22 10:08
Maybe you're using an incompatible version of LLVM? Which version of LLVM do you have?

**Comment by Teteros** [comment] 2021-04-25 19:37
I've bisected and this is caused by https://github.com/grame-cncm/faust/issues/573 in upstream FAUST.
Likely the cause of related build issues (cc #1289 #1126)

It's fixed in FAUST commit https://github.com/grame-cncm/faust/commit/5fbe04232cfcf28b3aa6e64a6dd4d9347f3735a8 and up.

**Comment by kmatheussen** [comment] 2021-04-26 17:59
https://github.com/kmatheussen/radium/commit/1de92910b28abd41a27ca3555158e3eaa3eb027d should fix it

**Closed** 2021-04-26 17:58 UTC
