### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mxmilkb** [kmatheussen/radium#1237] opened 2019-12-27 02:39 UTC
Trying to build from git via [AUR](https://aur.archlinux.org/packages/radium), getting this error:

```
...
externals/vanilla/nbx.c:757:17: warning: unused variable ‘f’ [-Wunused-variable]
  757 |     int lilo=0, f=0, ldx=0, ldy=-8;
      |                 ^
cc -o libs/libpd.so pure-data/src/g_canvas.o pure-data/src/g_graph.o pure-data/src/g_text.o pure-data/src/g_rtext.o pure-data/src/g_array.o pure-data/src/g_template.o pure-data/src/g_io.o pure-data/src/g_scalar.o pure-data/src/g_traversal.o pure-data/src/g_guiconnect.o pure-data/src/g_readwrite.o pure-data/src/g_editor.o pure-data/src/g_all_guis.o pure-data/src/m_pd.o pure-data/src/m_class.o pure-data/src/m_obj.o pure-data/src/m_atom.o pure-data/src/m_memory.o pure-data/src/m_binbuf.o pure-data/src/m_conf_pdextended.o pure-data/src/m_glob.o pure-data/src/m_sched.o pure-data/src/s_main.o pure-data/src/s_inter.o pure-data/src/s_file.o pure-data/src/s_loader.o pure-data/src/s_path.o pure-data/src/s_entry.o pure-data/src/s_audio.o pure-data/src/s_utf8.o pure-data/src/d_ugen.o pure-data/src/d_ctl.o pure-data/src/d_arithmetic.o pure-data/src/d_osc.o pure-data/src/d_filter.o pure-data/src/d_math.o pure-data/src/d_array.o pure-data/src/d_global.o pure-data/src/d_delay.o pure-data/src/d_resample.o pure-data/src/x_arithmetic.o pure-data/src/x_connective.o pure-data/src/x_acoustics.o pure-data/src/d_soundfile.o pure-data/src/e_fft.o pure-data/src/e_gfxstub.o pure-data/src/e_dac.o pure-data/src/e_midi.o pure-data/src/g_magicglass.o pure-data/src/import.o pure-data/src/path.o pure-data/src/closebang.o pure-data/src/initbang.o pure-data/src/s_print.o pure-data/src/d_fft_mayer.o pure-data/src/d_fftroutine.o pure-data/src/s_audio_dummy.o pure-data/extra/expr~/vexp_fun.o pure-data/extra/expr~/vexp_if.o pure-data/extra/expr~/vexp.o libpd_wrapper/s_libpdmidi.o libpd_wrapper/x_libpdreceive.o libpd_wrapper/z_libpd.o loader-file.o `./make.scm print-object-files` -shared -ldl -Wl,-Bsymbolic -lm -lpthread -lfftw3f -lfftw3 -logg -lvorbis -lvorbisfile -lvorbisenc -lspeex
bash -c "if ! libpds/bin2c libs/libpd.so >libpds/libpd_so.c ; then rm -f loader-file.c ; echo 'could not make loader-file.c' ; failed-failed-failed ; fi "
bash -c "if [[ ! -s libpds/libpd_so.c ]] ; then rm -f libpds/libpd_so.c ; echo 'could not make libpds/libpd_so.c' ; failed-failed-failed ; fi "
cc -DPD -DLIBPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util -DHAVE_LIBDL -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -fPIC -I"/usr/lib/jvm/default-java/include" -I"/usr/lib/jvm/default-java/include/linux" -O3 -g -D_GNU_SOURCE -Wall -o libs/libpds.so libpds/libpds.c -shared -ldl -Wl,-Bsymbolic -lm -ldl 
cc -DPD -DLIBPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util -DHAVE_LIBDL -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -fPIC -I"/usr/lib/jvm/default-java/include" -I"/usr/lib/jvm/default-java/include/linux" -O3 -g -D_GNU_SOURCE -Wall -c -o libpds.o libpds/libpds.c -lm -ldl
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[1]: *** [Makefile:165: libs/libpds.a] Error 1
make[1]: *** Waiting for unfinished jobs....
libpds/libpds.c: In function ‘libpds_create’:
libpds/libpds.c:74:94: warning: ‘%s’ directive writing up to 1023 bytes into a region of size 962 [-Wformat-overflow=]
   74 |     sprintf(error_string, "Unable to create libpds instance. Error message: \"%s\" Filename: %s", dlerror(), unlibered_filename);
      |                                                                                              ^~              ~~~~~~~~~~~~~~~~~~
libpds/libpds.c:74:5: note: ‘sprintf’ output 63 or more bytes (assuming 1086) into a destination of size 1024
   74 |     sprintf(error_string, "Unable to create libpds instance. Error message: \"%s\" Filename: %s", dlerror(), unlibered_filename);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libpds/libpds.c:53:48: warning: ‘%s’ directive writing up to 1023 bytes into a region of size 1003 [-Wformat-overflow=]
   53 |     sprintf(error_string,"Couldn't create file %s.",template);
      |                                                ^~
......
   69 |   if (write_libpd_so_to_tempfile(unlibered_filename)==false)
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libpds/libpds.c:53:5: note: ‘sprintf’ output between 23 and 1046 bytes into a destination of size 1024
   53 |     sprintf(error_string,"Couldn't create file %s.",template);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: Leaving directory '/home/milk/.cache/yay/radium/src/radium-5.9.86/bin/packages/libpd-master'
make: *** [Makefile:687: bin/packages/deletemetorebuild] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: radium
```

**Comment by mxmilkb** [comment] 2019-12-28 22:33
Log: https://travis-ci.com/mxmilkb/aur-av-bin/builds/142505216#L21801

**Comment by kmatheussen** [comment] 2019-12-29 19:55
I don't know what kind of build this is. The first error is this one:

Qt/helpers.h:611:12: error: 'start' is deprecated: Use QElapsedTimer
instead [-Werror,-Wdeprecated-declarations]

but Radium is not build with -Werror, at least not in RELEASE mode.
You might be able to solve it by adding "-Wno-deprecated-declarations" to
cflags though.

**Comment by mxmilkb** [comment] 2019-12-29 20:42
This is building on Arch Linux by using the PKGBUILD associated with radium AUR entry linked to above.

I've run locally again and [saved a proper log](https://gist.github.com/mxmilkb/b855b04233b197babe047bf59efe0284) that doesn't contain a "-Werror" (Travis should be building on the archlinux/base container but IDK there).

**Comment by kmatheussen** [comment] 2019-12-30 08:44
There's no error line in that log. This looks like the same error as this
ticket though: https://github.com/kmatheussen/radium/issues/1235

**Comment by Teteros** [comment] 2020-01-21 11:21
> Radium is not build with -Werror, at least not in RELEASE mode. You might be able to solve it by adding "-Wno-deprecated-declarations" to cflags though.

The four bin/radium source files to be compiled in Makefile.Qt at L1616-L1638 do contain "-Werror" regardless of running in debug/release build
https://github.com/kmatheussen/radium/blob/260da5f27915523824c379a54dbf4c523564985f/Makefile.Qt#L1616-L1638

Which throws deprecation errors on newer Qt5 versions.
Can be worked around by adding `-Wno-error=deprecated-declarations -Wno-missing-declarations` at the end of those lines of course and radium 5.9.90 on arch builds with this.

@mxmilkb I've patched the above into the PKGBUILD.

**Comment by kmatheussen** [comment] 2020-01-21 12:01
Thank you, didn't know about that. I've removed most -Werror from non-debug
builds in 53b334da968c0d16f6257c2f53085f101afaf244.

**Comment by mxmilkb** [comment] 2020-01-22 01:26
@Teteros Thanks, trying the PKGBUILD from the AUR again, but it fails, same error as my first msg;

```
externals/vanilla/hradio.c:551:48: warning: unused variable ‘fthold’ [-Wunused-variable]
  551 |     int ftbreak=IEM_BNG_DEFAULTBREAKFLASHTIME, fthold=IEM_BNG_DEFAULTHOLDFLASHTIME;
      |                                                ^~~~~~
externals/vanilla/hradio.c:551:9: warning: unused variable ‘ftbreak’ [-Wunused-variable]
  551 |     int ftbreak=IEM_BNG_DEFAULTBREAKFLASHTIME, fthold=IEM_BNG_DEFAULTHOLDFLASHTIME;
      |         ^~~~~~~
externals/vanilla/hradio.c:548:38: warning: unused variable ‘f’ [-Wunused-variable]
  548 |     int a=IEM_GUI_DEFAULTSIZE, on=0, f=0;
      |                                      ^
Executing command - gcc -O3 -Wall -g -DPD -DVERSION=\"libpd-extended-0.43.3\" -Ipure-data/src/ -DLIBPD -fPIC -I/usr/include/tirpc   -Dsetup=setup_libpd_hsl0x2ec -c externals/vanilla/hsl.c -o externalobjs/hsl.c.o - 
externals/vanilla/hsl.c: In function ‘hslider_new’:
externals/vanilla/hsl.c:535:10: warning: unused variable ‘str’ [-Wunused-variable]
  535 |     char str[144];
      |          ^~~
externals/vanilla/hsl.c:532:33: warning: unused variable ‘f’ [-Wunused-variable]
  532 |     int lilo=0, ldx=-2, ldy=-8, f=0, v=0, steady=1;
      |                                 ^
Executing command - gcc -O3 -Wall -g -DPD -DVERSION=\"libpd-extended-0.43.3\" -Ipure-data/src/ -DLIBPD -fPIC -I/usr/include/tirpc   -Dsetup=setup_libpd_cnv0x2ec -c externals/vanilla/cnv.c -o externalobjs/cnv.c.o - 
externals/vanilla/cnv.c: In function ‘my_canvas_dialog’:
externals/vanilla/cnv.c:191:9: warning: unused variable ‘sr_flags’ [-Wunused-variable]
  191 |     int sr_flags = iemgui_dialog(&x->x_gui, srl, argc, argv);
      |         ^~~~~~~~
externals/vanilla/cnv.c: In function ‘my_canvas_new’:
externals/vanilla/cnv.c:269:10: warning: unused variable ‘str’ [-Wunused-variable]
  269 |     char str[144];
      |          ^~~
externals/vanilla/cnv.c:267:25: warning: unused variable ‘f’ [-Wunused-variable]
  267 |     int ldx=20, ldy=12, f=2, i=0;
      |                         ^
Executing command - gcc -O3 -Wall -g -DPD -DVERSION=\"libpd-extended-0.43.3\" -Ipure-data/src/ -DLIBPD -fPIC -I/usr/include/tirpc   -Dsetup=setup_libpd_nbx0x2ec -c externals/vanilla/nbx.c -o externalobjs/nbx.c.o - 
externals/vanilla/nbx.c: In function ‘my_numbox_new’:
externals/vanilla/nbx.c:761:10: warning: unused variable ‘str’ [-Wunused-variable]
  761 |     char str[144];
      |          ^~~
externals/vanilla/nbx.c:757:17: warning: unused variable ‘f’ [-Wunused-variable]
  757 |     int lilo=0, f=0, ldx=0, ldy=-8;
      |                 ^
cc -o libs/libpd.so pure-data/src/g_canvas.o pure-data/src/g_graph.o pure-data/src/g_text.o pure-data/src/g_rtext.o pure-data/src/g_array.o pure-data/src/g_template.o pure-data/src/g_io.o pure-data/src/g_scalar.o pure-data/src/g_traversal.o pure-data/src/g_guiconnect.o pure-data/src/g_readwrite.o pure-data/src/g_editor.o pure-data/src/g_all_guis.o pure-data/src/m_pd.o pure-data/src/m_class.o pure-data/src/m_obj.o pure-data/src/m_atom.o pure-data/src/m_memory.o pure-data/src/m_binbuf.o pure-data/src/m_conf_pdextended.o pure-data/src/m_glob.o pure-data/src/m_sched.o pure-data/src/s_main.o pure-data/src/s_inter.o pure-data/src/s_file.o pure-data/src/s_loader.o pure-data/src/s_path.o pure-data/src/s_entry.o pure-data/src/s_audio.o pure-data/src/s_utf8.o pure-data/src/d_ugen.o pure-data/src/d_ctl.o pure-data/src/d_arithmetic.o pure-data/src/d_osc.o pure-data/src/d_filter.o pure-data/src/d_math.o pure-data/src/d_array.o pure-data/src/d_global.o pure-data/src/d_delay.o pure-data/src/d_resample.o pure-data/src/x_arithmetic.o pure-data/src/x_connective.o pure-data/src/x_acoustics.o pure-data/src/d_soundfile.o pure-data/src/e_fft.o pure-data/src/e_gfxstub.o pure-data/src/e_dac.o pure-data/src/e_midi.o pure-data/src/g_magicglass.o pure-data/src/import.o pure-data/src/path.o pure-data/src/closebang.o pure-data/src/initbang.o pure-data/src/s_print.o pure-data/src/d_fft_mayer.o pure-data/src/d_fftroutine.o pure-data/src/s_audio_dummy.o pure-data/extra/expr~/vexp_fun.o pure-data/extra/expr~/vexp_if.o pure-data/extra/expr~/vexp.o libpd_wrapper/s_libpdmidi.o libpd_wrapper/x_libpdreceive.o libpd_wrapper/z_libpd.o loader-file.o `./make.scm print-object-files` -shared -ldl -Wl,-Bsymbolic -lm -lpthread -lfftw3f -lfftw3 -logg -lvorbis -lvorbisfile -lvorbisenc -lspeex
bash -c "if ! libpds/bin2c libs/libpd.so >libpds/libpd_so.c ; then rm -f loader-file.c ; echo 'could not make loader-file.c' ; failed-failed-failed ; fi "
bash -c "if [[ ! -s libpds/libpd_so.c ]] ; then rm -f libpds/libpd_so.c ; echo 'could not make libpds/libpd_so.c' ; failed-failed-failed ; fi "
cc -DPD -DLIBPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util -DHAVE_LIBDL -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -fPIC -I"/usr/lib/jvm/default-java/include" -I"/usr/lib/jvm/default-java/include/linux" -O3 -g -D_GNU_SOURCE -Wall -o libs/libpds.so libpds/libpds.c -shared -ldl -Wl,-Bsymbolic -lm -ldl 
cc -DPD -DLIBPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util -DHAVE_LIBDL -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -fPIC -I"/usr/lib/jvm/default-java/include" -I"/usr/lib/jvm/default-java/include/linux" -O3 -g -D_GNU_SOURCE -Wall -c -o libpds.o libpds/libpds.c -lm -ldl
cc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[1]: *** [Makefile:165: libs/libpds.a] Error 1
make[1]: *** Waiting for unfinished jobs....
libpds/libpds.c: In function ‘libpds_create’:
libpds/libpds.c:74:94: warning: ‘%s’ directive writing up to 1023 bytes into a region of size 962 [-Wformat-overflow=]
   74 |     sprintf(error_string, "Unable to create libpds instance. Error message: \"%s\" Filename: %s", dlerror(), unlibered_filename);
      |                                                                                              ^~              ~~~~~~~~~~~~~~~~~~
libpds/libpds.c:74:5: note: ‘sprintf’ output 63 or more bytes (assuming 1086) into a destination of size 1024
   74 |     sprintf(error_string, "Unable to create libpds instance. Error message: \"%s\" Filename: %s", dlerror(), unlibered_filename);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libpds/libpds.c:53:48: warning: ‘%s’ directive writing up to 1023 bytes into a region of size 1003 [-Wformat-overflow=]
   53 |     sprintf(error_string,"Couldn't create file %s.",template);
      |                                                ^~
......
   69 |   if (write_libpd_so_to_tempfile(unlibered_filename)==false)
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libpds/libpds.c:53:5: note: ‘sprintf’ output between 23 and 1046 bytes into a destination of size 1024
   53 |     sprintf(error_string,"Couldn't create file %s.",template);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: Leaving directory '/home/milk/.cache/yay/radium/src/radium-5.9.90/bin/packages/libpd-master'
make: *** [Makefile:687: bin/packages/deletemetorebuild] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: radium
yay -S --answeredit n radium  3395.18s user 141.56s system 243% cpu 24:10.89 total
```

**Comment by kmatheussen** [comment] 2020-01-22 11:44
Your backtrace doesn't contain the actual error, only irrelevant warnings. But I'm pretty sure this is a duplicate of #1235, so I'm closing this one.

**Closed by kmatheussen** 2020-01-22 11:44 UTC
