### ISSUE TITLE
Can't compile latest master (ratio2double was not declared)

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1403] opened 2023-04-16 14:32 UTC
Hi, I have an error when trying to compile latest Radium:

```
In file included from embedded_scheme/scheme.cpp:37:
embedded_scheme/../common/ratio_funcs.h: In member function ‘const char* r::RatioPeriod::to_string() const’:
embedded_scheme/../common/ratio_funcs.h:422:32: error: ‘ratio2double’ was not declared in this scope
  422 |       sprintf(ret, "%f -> %f", ratio2double(_start), ratio2double(_end));
      |                                ^~~~~~~~~~~~
In file included from audio/../common/TimeData.hpp:82,
                 from audio/audio_instrument.cpp:20:
audio/../common/ratio_funcs.h: In member function ‘const char* r::RatioPeriod::to_string() const’:
audio/../common/ratio_funcs.h:422:32: error: ‘ratio2double’ was not declared in this scope
  422 |       sprintf(ret, "%f -> %f", ratio2double(_start), ratio2double(_end));

```
Maybe something is not commited to repository.

**Comment by kmatheussen** [comment] 2023-04-16 14:36
Thanks, fixed now. It was caused by cherry-picked a commit from the
timedata_notes branch.

**Closed** 2023-04-16 14:38 UTC

**Comment by akimaze** [comment] 2023-04-16 14:59
Thanks, Now I get another ratio related error:

```
common/ratio_funcs.h: In function ‘RATIO_div’:
common/ratio_funcs.h:122:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  122 |     Ratio r2_inverted{-r2.den, -r2.num};
      |                      ^
common/ratio_funcs.h:122:30: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  122 |     Ratio r2_inverted{-r2.den, -r2.num};
      |                              ^
common/ratio_funcs.h:122:30: warning: statement with no effect [-Wunused-value]
common/ratio_funcs.h:122:39: error: expected ‘;’ before ‘}’ token
  122 |     Ratio r2_inverted{-r2.den, -r2.num};
      |                                       ^
      |                                       ;
common/ratio_funcs.h:123:26: error: ‘r2_inverted’ undeclared (first use in this function)
  123 |     return RATIO_mul(r1, r2_inverted);
      |                          ^~~~~~~~~~~
common/ratio_funcs.h:123:26: note: each undeclared identifier is reported only once for each function it appears in
In file included from common/hashmap.c:27:
common/ratio_funcs.h: In function ‘RATIO_div’:
common/ratio_funcs.h:125:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  125 |     Ratio r2_inverted{r2.den, r2.num};
      |                      ^
common/ratio_funcs.h:125:29: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  125 |     Ratio r2_inverted{r2.den, r2.num};
      |                             ^
common/ratio_funcs.h:125:29: warning: statement with no effect [-Wunused-value]
common/ratio_funcs.h:125:37: error: expected ‘;’ before ‘}’ token
  125 |     Ratio r2_inverted{r2.den, r2.num};
      |                                     ^
      |                                     ;
common/ratio_funcs.h:122:22: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  122 |     Ratio r2_inverted{-r2.den, -r2.num};
```

**Comment by kmatheussen** [comment] 2023-04-16 15:47
Try now

**Comment by akimaze** [comment] 2023-04-16 16:21
> Try now

Success, thanks again :)
