### ISSUE TITLE
graphic bug

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#387] opened 2015-12-30 11:30 UTC
hi

track head flash when sound playing sometime and pattern editor gone after and mouse don't work
i have tested radium on 3 pc is same , when i work a lot of time on music, radium get crazy , like if the memory is full , big graphic bug , mouse uncontrolable... :(

cu bye

**Comment by kmatheussen** [comment] 2015-12-30 14:13
Hi, that's not good. I think I have seen something similar a long time ago, but can you describe more about when it happens? I probably need to be able to reproduce the problem in order to fix it. Do you just do some use the program for a while, and suddenly this happens?

Does the problem disappear if you load a new song, or change block? Or do you have to restart the program?

Is this on windows?
Is the same graphic driver on all the all 3 pcs? (probably not very likely)

**Comment by onukore** [comment] 2015-12-30 22:43
i used 4 track with sampler with automation on sample star, pan,note glissendo, 2 vsti with automation filter, reverb  and some fx

that happen always when i work a lot , it isn't a cpu problem im under 20 % in midl

when i load new song is same, i need to restart radium

yes windows 7 in 3 pc with nvidia and intel graphic gpu

**Comment by kmatheussen** [comment] 2015-12-31 09:26
I'm going to send you privately an experimental version later. But can you try this first?:

Delete everything between line 215 and line 223 in the file bin/scheme/mouse.scm . I.e. these lines:
```
          ;; dirty trick to avoid the screen edges
          (when mouse-pointer-is-hidden
            (when (or (< (ra:get-mouse-pointer-x) 16)
                      (< (ra:get-mouse-pointer-y) 16)
                      (> (ra:get-mouse-pointer-x) 500)
                      (> (ra:get-mouse-pointer-y) 500))
              (ra:move-mouse-pointer 100 100)
              ;;(c-display "x/y" (ra:get-mouse-pointer-x) (ra:get-mouse-pointer-y))
              (set! prev-x 100)
              (set! prev-y 100)))
```

It's probably not going to make a difference, but since you said the mouse was uncontrollable, it's worth a try.

Actually, I wonder what you mean by the mouse being uncontrollable. Can you describe more what happens? Is the mouse pointer jumping around on itself, does it move in opposite direction, etc.?

**Comment by onukore** [comment] 2015-12-31 11:13
the mouse stay on 1/4 upper left of screen , can't move in modular (ex), the screen flash  in block tempo multiplier slider bar, the track header flash, and the block gone, but the sound continue,at the end radium crash

ps when i copy block the automation are copy to in the new block , why you don't use this process to copy rang or track copy ?

**Comment by kmatheussen** [comment] 2015-12-31 11:37
Thanks, that's very useful information. Delete those lines between line 215 and line 223 should at least fix the mouse problem.

> ps: when i copy block the automation are copy to in the new block , why you don't use this process to copy rang or track copy ?

Are you saying that automation is not copied when you copy range or track?

**Comment by onukore** [comment] 2015-12-31 11:53
yes the automation is not copied when you copy range (not track ,sorry my bad)

**Comment by kmatheussen** [comment] 2015-12-31 12:58
Ok. I'll look at range copy. Please also mail me privately. I tried to email you, but you didn't repyl. I have a new version of Radium which might fix the graphics bug.

**Comment by kmatheussen** [comment] 2016-01-06 12:05
Can we close this one now? Has the graphic crash bug disappeared?

**Comment by onukore** [comment] 2016-01-07 09:04
i think it's ok no bug back

**Closed** 2016-01-09 19:31 UTC
