### ISSUE TITLE
osx(sierra):impossible to enter numbers in pattern editor  

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#857] opened 2017-02-18 11:20 UTC
hi !
I  can enter numbers anywhere but not in editor .
I think the bigger problem on sierra is editor , (scroll lag (but sound work well ), keyboard input pb, back ground color bug etc..)

dear !

**Comment by onukore** [comment] 2017-02-20 08:30
hi
can you fix the numbers issue please, after that radium work fine on Sierra, please , (only some vst gui issues with automation (HY-mono, tunefish 4..) but no sound issue

**Comment by kmatheussen** [comment] 2017-02-20 09:20
Is the problem that the number keys don't work?
In case, can you enable "Show key codes" under preferences -> Various
and tell me the rightmost number that is shown in the editor when
you press the number keys?

**Comment by kmatheussen** [comment] 2017-02-20 09:37
This is the numbers you are supposed to see:
18,19,20,21,22,23,24,25,26,27,28,29
(for the keys 1,2,3,4,5,6,7,8,9,0)

**Comment by onukore** [comment] 2017-02-20 10:28
i see:
18,19,20,21,23,22,26,28,25,29

**Comment by kmatheussen** [comment] 2017-02-20 10:33
I guess that's correct. So if you press the '2' key, the one above 'q' and
'w'
(or 'a' and 'z' if you use a french keyboard), nothing happens?

**Comment by onukore** [comment] 2017-02-20 10:44
when only '2' I have sound (c#4), with shift for numbers in velocity track , nothing happen.
I think edit line problem (ctrl+1,2,3 etc) as same issue (ctrl+z work fine, not ctrl issue)

**Comment by onukore** [comment] 2017-02-20 12:09
an other thing, when I enter note with (2,3,5,6,7)(c#4,d#4 etc ..) the editor stay in the same position, not like with a,z,e,r etc .. that move to the next line position

**Comment by kmatheussen** [comment] 2017-02-23 10:35
> when only '2' I have sound (c#4), with shift for numbers in velocity track , nothing happen.

I've tried various things on sierra now, and everything seems to work.
Is this what you do?

1. Add C#4 by pressing '2'.
2. Enable velocity text
3. Move cursor to velocity text track
4. Press shift + 2.
5. Nothing happens.
?

> an other thing, when I enter note with (2,3,5,6,7)(c#4,d#4 etc ..) the editor stay in the same position, not like with a,z,e,r etc .. that move to the next line position

I can't reproduce this either. Can you test again?

**Comment by onukore** [comment] 2017-02-23 13:12
nothing work for me
1- press '2' add c#4 ok but stay in same position 
2- enable velocity track ,move to track txt, press 2 ( create c#4 note) or shift+2  nothing happen 
i 've test on renoise and other software no problem
maybe problem with French keyboard ?

**Comment by kmatheussen** [comment] 2017-02-24 09:06
It's still not clear what you try to do.

In point 2 in your recipe, it seems like you
try to create a c#4 note by pressing the '2' key.
A c#4 note is not supposed to be created when
you press the '2' key while the cursor is placed
in the velocity text track.

**Comment by onukore** [comment] 2017-02-24 17:55
hi

haha !! 
when I press '2' in velocity track text I create note C#4, when I press 'shift +2' nothing happen

**Comment by kmatheussen** [comment] 2017-02-26 13:51
Got it. I could reproduce it when switching to french keyboard.

**Comment by kmatheussen** [comment] 2017-02-26 16:07
This seems a bit crazy. Do you have to press shift+1 to write 1 on a french
keyboard?
Isn't that very inconvenient? ;-)

It also makes the keyboard handling in Radium even more complicated since
the program
assumes that there exist single-press keys that writes '1', '2', '3', etc.
The fact
that it worked to add C# notes is just a coincidence.
The keyboard handling started using some fallback code that uses scancodes
instead.
I.e. it ignore locale settings and read key info directly from hardware). I
guess the simple solution
is to use this fallback code for text tracks as well. Hopefully there are
no keyboard
configuration where the number keys are placed in non-standard positions.





On Sun, Feb 26, 2017 at 2:51 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> Got it. I could reproduce it when switching to french keyboard.
>

**Comment by onukore** [comment] 2017-02-26 16:48
hi

French keyboard always made problems ( aodix, renoise 've bugs, before I've ask to devs (arguru (rip) and taktik) 

yes it will be better if I press only 1,2 (like in renoise) etc to enter number , no problem if I need to press shift , if is not possible
-another thing track pad scroll well (two finger) bug on editor (with mouse no problem)
-HY vst  plugs very unstable on radium 
- editor background color bug ( when I change it , it going black, with picked color that work)

**Comment by kmatheussen** [comment] 2017-02-26 19:45
Should be fixed now. Don't need to press shift.

**Closed by kmatheussen** 2017-02-26 19:45 UTC
