### ISSUE TITLE
Draw in separate process crashes OSX (was: Black Editor Window Bug ---> Possible Pattern found...)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#948] opened 2017-04-23 18:25 UTC
###Hi,

can you try the following?
When I do this, I can repeat and recreate the "Black Editor Window" Bug all the time.

- Modular Mixer and Sequencer Window open, Main Editor Window **hidden**.
- Sequencer Track  1 Has Blocks in it
- Sequencer Track 2 is empty
- with **second** sequencer track selected: On a VST parameter,  do: 
  **add automation to current sequencer track**.
- show main editor window again, should be black now. 

Radium should freeze then on quit or loading another song.
When force quit, no crash report... 

Could you check this if you get something similar like this?

**Comment by Lykdraft** [comment] 2017-04-23 18:45
> Modular Mixer and Sequencer Window open, Main Editor Window hidden.
Sequencer Track 1 Has Blocks in it


Actually it seems you just have to append sequencer track after this and the main editor goes black.

**Comment by kmatheussen** [comment] 2017-04-23 19:13
Thank you very much. I can't reproduce it on Linux, but I'll try OSX and
Windows later.
Can you try to disable "Draw in separate process" under edit -> preferences
-> OpenGL -> Various?
It might help.

**Comment by Lykdraft** [comment] 2017-04-23 19:41
Looks like it indeed helps, thanks.
I can close this again, but you might want to try out the pattern to the black editor on OSX anyways
to see if this is recreatable?

Best,
tL.

**Comment by kmatheussen** [comment] 2017-04-23 19:42
Yes, this is a bug. Don't close yet. :-)

**Comment by kmatheussen** [comment] 2017-06-06 19:30
I hope this is fixed in the latest release. I enabled "draw in separate process" again on OSX.

**Comment by kmatheussen** [comment] 2017-06-14 08:41
> Could you check this if you get something similar like this?

Just discovered another problem with draw in separate process that sounds very similar to the problem you describe here. There is a potential deadlock that happens if playing song while there is no blocks in the current sequencer track. When I followed your recipe above, while playing song, I did reproduce the deadlock on linux. 

Going to fix this, of course. I also think I'm going to just show a blank text in the editor saying "No blocks playing in the current sequencer track", or something similar, instead of drawing the last played block. It's a little bit confusing now, especially since you can't edit or navigate in this block.

**Comment by kmatheussen** [comment] 2017-06-14 11:04
> a blank text 

A blank window rather, except the text.

**Comment by kmatheussen** [comment] 2017-06-17 09:21
I'm pretty sure this bug is fixed now. Some drivers might crash though, but that's a bug in the drivers.

**Closed by kmatheussen** 2017-06-17 09:21 UTC
