### ISSUE TITLE
Support LLVM-7

### ISSUE THREAD

**Issue by muziker** [kmatheussen/radium#1174] opened 2019-03-18 19:05 UTC
I'd like to request the following packages be upgraded.
From the older versions to Faust 2.15, LLVM 7.0

**Comment by Teteros** [comment] 2019-03-20 00:26
Duplicate of #1068
My last porting effort was for 5.0.0 (#1069) but the embedded faust package has proven to be too old for simple backports from master faust2 repo as time went on.

**Comment by muziker** [comment] 2019-04-11 02:32
I had a go at figuring this out a few weeks ago. I had to replace references to faustqt.h with QTUI.h, especially in the qtcompile makefiles, because faust 2.15 had changed it's header filename ( looks like a drop in replacement) There doesn't seem to be much difference there. Also IIRC, one of the faust dsp file has this strange circularity where referring a variable gets defined twice, but once compilation gets past that point, it has to be reenabled. There's also a division by zero in a dsp file, but setting it to a small number makes it work. I'm not sure if that helps.

But at any rate, it managed to compile right to the final end where linking everything together generated an error that i didn't have time to figure out why.

**Comment by kmatheussen** [comment] 2019-04-11 06:59
I have llvm 8 working here. Working on adding support for the faust
interpreter backend in addition to the llvm backend.

**Comment by kmatheussen** [comment] 2019-04-26 08:36
Closing issue since I'm pretty sure it works now. If it doesn't work, please re-open.

**Closed by kmatheussen** 2019-04-26 08:36 UTC
