### ISSUE TITLE
Sequencer tracks resizing display problem

### ISSUE THREAD

**Issue by ecodjtal** [kmatheussen/radium#1165] opened 2019-02-04 16:49 UTC
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: create multiple sequencer tracks
* Step 3: hide the main window lower tabs using f8 keyboard shortcut
* Step 4: press f8 again to show the sequencer tracks again

* I expected this to happen: the sequencer tracks should all be displayed 

* This is what actually happened: the sequencer tracks don't show up except the first one (see video below)

* everything goes back to normal as soon as i resize the sequencer window

...

### 3. My operating system is Manjaro i3 edition 18.0.2

https://vimeo.com/315264739

**Comment by kmatheussen** [comment] 2019-02-04 16:54
Thanks for the report. I've seen something similar, but I haven't made a
clean reproducable case for it.
The problem isn't that it only display the first seqtrack, the problem
is that it only display the last seqtrack. So you have to scroll up
in order to see the first three seqtracks as well. You can scroll up
by using the scroll wheel on the mouse (place the mouse cursor inside
the seqtrack headers), or move the navigator.

**Comment by ecodjtal** [comment] 2019-02-04 16:57
okay thank you for the quick reply, if there is anything i can do to help make this a reproducible case feel free to tell me.

should i close this issue ?

**Comment by ecodjtal** [comment] 2019-02-04 17:05
no problem, thanks for the awesome software btw

**Comment by kmatheussen** [comment] 2019-02-04 21:43
Think it's fixed now. Strange bug. Seemed like it was caused by a Qt quirk.

**Closed by kmatheussen** 2019-02-04 21:43 UTC
