### ISSUE TITLE
rang play unstable

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#357] opened 2015-08-29 09:12 UTC
- range not perfect loop,
- when i move mouse ,range jump .
- when open vst gui big buffer overdrive , i have a try lot of jackaudio config but it's the same
- when tack selected in track header crash box open ( when song play) some times
- unstable release than the last
but i love scroll lock it's exactly what i mind

**Comment by kmatheussen** [comment] 2015-08-30 07:01
> range not perfect loop,

Yes, the range loop is definitely not always perfect. The main thread is just frequently checking the play position, and restarts playing if it reaches range end. Doing it differently is very complicated, so I guess you have to live with it. I thought the main point about playing range loop was to immediately hear the difference while editing a minor part of the block. For that purpose, I think the current behavior should be good enough...

> when open vst gui big buffer overdrive , i have a try lot of jackaudio config but it's the same

You mean that you hear glitches in sound when you open a VST gui? That sometime happens for some plugins, but I don't think Radium should ever be the cause of this. Can you name a VST plugin where this happens, so that I can check?

> when tack selected in track header crash box open ( when song play) some times

I don't understand what you do here. Can you explain again? Also, are you pressing "Send" when the crash reporter window is shown? I don't think I have any unsolved crash reports. (Maybe you have a firewall so that the reports are never sent?)

**Comment by onukore** [comment] 2015-08-30 08:52
i found the bug , when piano roll is open in track and i select it with left mouse clic ,crash happen, not happen if no piano roll 
the plug in is oatmeal

**Comment by kmatheussen** [comment] 2015-08-30 09:10
I'm a bit lost here.
1. Has oatmeal anything to co with the crash?
2. I still haven't received any crash report. Do you click "Send" when the crash reporter window opens?
3. In the sentence "when piano roll is open in track and i select it with left mouse clic", what does "it" refer to? And where exactly are you clicking?

**Comment by kmatheussen** [comment] 2015-08-30 09:26
Thank you, I got report now. It's not a crash though, it's just a warning that Radium is in a state it should not be in. When I look at the code, it's not even that, it's just an unnecessary warning, so just ignore it. The warning will be removed in the next version.

**Comment by onukore** [comment] 2015-08-30 09:29
ok fine

**Comment by kmatheussen** [comment] 2015-09-15 13:28
If you need a perfect range loop, just make a new issue about it, and explain why it would be useful. Closing this issue. I also made a separate issue about the vst problem (haven't had time to look at it yet).

**Closed by kmatheussen** 2015-09-15 13:28 UTC
