### ISSUE TITLE
Unable to use Scrollwheel for VST preset selection (Doesn't work anymore)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#700] opened 2016-10-06 23:31 UTC
Hey,

I noticed that I am not able anymore to select plugin presets (the numbers besides the preset name)
via the scrollwheel anymore. This used to work. I am not sure since when it stopped to work.

I noticed that already some time ago but I forgot to mention it. 

Best,
tL.

**Comment by onukore** [comment] 2016-10-07 12:32
that  work for me (on windows)

**Comment by kmatheussen** [comment] 2016-10-08 14:00
I tried to reproduce this now, and the scroll wheel didn't work. After that I tried to change a volume value in the note duplicator with the scroll wheel, and that worked. And when I tried to change vst plugin preset with the scroll wheel, it also worked. And after that I was not able to reproduce the problem at all, not even after restarting Radium. I have also looked at the code, and it seems fine. Is it permanently not working for you, or does it work now and then?

**Comment by kmatheussen** [comment] 2016-10-08 15:50
Also, does the sound change, or is it just the graphics that isn't updated?

**Comment by Lykdraft** [comment] 2016-10-10 14:40
Testing the new build right and it seems to work (again?).
So maybe this was just some odd hickup somewhere, not sure.
I'll close this for now.

**Comment by kmatheussen** [comment] 2016-10-10 14:51
It did happen once for me, so something is not right. I don't think I changed anything in the last release that could have fixed this, so I'm reopening the issue so that it won't be forgotten.

**Comment by Lykdraft** [comment] 2016-10-10 23:25
ok, cool. By the way, maybe it's a good idea to swap the position of the preset name and the number box, so that the box with the number doesn't always jump left and right on loading another preset.

Right now we often have to "lookup" the position of the number box after preset change, because the lenght of the preset name is often changing so much, that the numberbox is at a very different place all the time..

**Comment by kmatheussen** [comment] 2016-10-13 07:11
Yes, swapped the position now. Good idea. Also moved the "solo" button so that it's anchored to the right border.

I experienced the scroll wheel problem now, this time (as last time) on OSX. It helped just clicking the number box. This seems like a Qt thing (i.e. the GUI set), and it will hopefully be automatically fixed in a future release.

**Comment by kmatheussen** [comment] 2016-10-14 09:50
> that work for me (on windows) but that dosen't works in vst gui, in renoise i can use scroll wheel in vst ( ex sampletank to navigate in preset browser but not in radium (never works)

Are you saying that the scroll wheel doesn't work in the native VST guis?

**Comment by onukore** [comment] 2016-10-15 07:29
hi
yes in some vst's gui not in all, in sampletank 2 scroll wheel work on renoise not in radium

**Comment by kmatheussen** [comment] 2016-10-15 07:46
Hi, when you use the scroll wheel, does it work on Radium instead? I.e. does the editor scroll up and down instead of changing preset inside the VST plugin?

**Comment by onukore** [comment] 2016-10-16 08:56
yes, scroll wheel work fine in radium , just some vst gui ( sampletank )

**Comment by Lykdraft** [comment] 2016-11-16 00:17
FYI: Stopped working completely.

**Comment by Lykdraft** [comment] 2016-11-16 00:19
Maybe a key command implementation would be better.
so that we can go to prev/next preset with the module selected per hotkey.
Much faster anyways. (Or a "Select random preset" button would be fun I think. Or some "<" ">" arrow buttons or something.

**Closed** 2019-02-24 03:47 UTC
