### ISSUE TITLE
Radium 3.7.6 crashes on start on OSX.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#485] opened 2016-04-18 11:57 UTC
Nothing more to say about that.
3.7.6 Crashes on load. Can't open it.

interesting is that thread 42 crashed, which is unusual,
so lookung up thread 42 I see some render and GL related things I guess?
OSX 10.10.4

____________
Thread 42 Crashed:: QThread
0   www.notam02.no                	0x0000000107e10311 vl::Viewport::activate() const + 545
1   www.notam02.no                	0x0000000107dd158f vl::Renderer::render(vl::RenderQueue const*, vl::Camera*, float) + 207
2   www.notam02.no                	0x0000000107dd612d vl::Rendering::render() + 2653
3   www.notam02.no                	0x0000000107c4cb7c MyQt4ThreadedWidget::draw(bool) + 5532
4   www.notam02.no                	0x0000000107c4aec6 MyQt4ThreadedWidget::updateEvent() + 662
5   www.notam02.no                	0x0000000107c51c4d vl::OpenGLContext::dispatchResizeEvent(int, int) + 189
6   www.notam02.no                	0x0000000107c51626 vlQt4::Qt4ThreadedWidget::MyThread::run() + 150
7   QtCore                        	0x000000010a1bba40 0x10a196000 + 154176
8   libsystem_pthread.dylib       	0x00007fff8bdc605a _pthread_body + 131
9   libsystem_pthread.dylib       	0x00007fff8bdc5fd7 _pthread_start + 176
10  libsystem_pthread.dylib       	0x00007fff8bdc33ed thread_start + 13

Thread 42 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00006180002da0f0  rcx: 0x0000000000000000  rdx: 0x00007fff714f41f8
  rdi: 0x0009710000097203  rsi: 0x0009720000097200  rbp: 0x0000000116ce7920  rsp: 0x0000000116ce78e0
   r8: 0x0000000116ce7890   r9: 0x0000000116ce8000  r10: 0x0000000000000008  r11: 0x0000000000000246
  r12: 0x00000000000003e8  r13: 0x00000000000003e8  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000107e10311  rfl: 0x0000000000000202  cr2: 0x0000000107cc6080

**Comment by kmatheussen** [comment] 2016-04-18 12:02
I just discovered this as well when checking out the color configuration
things.
It's probably because it tries to render graphics during startup (after
loading file)
now, to avoid allocating gradient triangles during playback.
Unfortunately I just screwed up my build environment as well, so it could
take
some hours before a new release.

**Comment by kmatheussen** [comment] 2016-04-24 14:42
should be fixed. At least the regression in 3.7.6 is fixed, although the general problem is still there.

**Closed by kmatheussen** 2016-04-24 14:42 UTC
