### ISSUE TITLE
start crash on 3.30

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#345] opened 2015-08-11 08:51 UTC
hi kmatheussen

clic on exe, crash box open that all 
in 3.29 num lock revese when is on track navigation don't works, when is off that works

by

**Comment by kmatheussen** [comment] 2015-08-11 09:00
> clic on exe, crash box open that all 

Did this only happen in 3.3.0, or does it happen in 3.2.9 too?


> in 3.29 num lock revese when is on track navigation don't works, when is off that works

Added to this issue: https://github.com/kmatheussen/radium/issues/342
The problems are related.

**Comment by onukore** [comment] 2015-08-11 09:24
yes only in 3.30 , radium do not start, just logo, before crashing

**Comment by kmatheussen** [comment] 2015-08-11 09:34
Thanks for the quick heads up. I'll remove 3.3.0 from the webpage now, and try to fix this when I get home later today.

**Comment by kmatheussen** [comment] 2015-08-11 09:39
By the way, which windows version are you using? Was it 64 bit Windows 7?

**Comment by onukore** [comment] 2015-08-11 10:01
thanks to you for you're works

i use win 7 64 bit, on laptop 8gb ram , 460 gtx nvdia, core i7 quadcore , i use asio4all because my motu ultralite mk3 fw dosen't works with jack (asio native will be better for me but , if not ,this is not a probleme for me, for recordind i use other daw) , i use 32 bit version of radium because almost vst i use ,are in 32 bit

**Comment by kmatheussen** [comment] 2015-08-11 10:08
Thanks. I think I know what the problem is now. I re-enabled an option which previously made Radium crash, but I didn't check the 32 bit version. I guess the 64 bit version of radium 3.3.0 works:
http://users.notam02.no/~kjetism/radium/demos/windows64/notworkingverywell/radium_64bit_windows-3.3.0-demo.zip

**Comment by onukore** [comment] 2015-08-11 11:48
yes that works, but 32 bit plugs dosen't works ;) 
 a little bug  in piano roll, impossible to enter c-4 note by clic on it, i enter c#4 and i move it to c-4

**Comment by kmatheussen** [comment] 2015-08-12 07:31
> a little bug in piano roll, impossible to enter c-4 note by clic on it, i enter c#4 and i move it to c-4

It's more of a design bug. If you click in the leftmost part of the piano roll, you will change track width instead. Maybe it would be better if it was only possible to change track width in the track header.

**Comment by onukore** [comment] 2015-08-12 13:39
hi
yes  i think too,  and colors shema it's to complicated
the same color for different thing is too confusing( for me )

**Comment by onukore** [comment] 2015-08-12 14:00
i have found a solution for c-4 problem, i have enlarge the note range in track header , that work fine now, but with automation ,if it is completely left we can not take off the edge

**Comment by kmatheussen** [comment] 2015-08-14 17:36
> yes i think too, and colors shema it's to complicated
> the same color for different thing is too confusing( for me )

Hi, can you elaborate? Which part of the program are you talking about, and what do you think should be different?

**Comment by onukore** [comment] 2015-08-15 08:27
hi, i think about botton and sliders colors and wav name in transpose box and sampler widget, color in sample navigation 
![capture d ecran 2015-08-15 10 22 24](https://cloud.githubusercontent.com/assets/13727495/9288147/2bda0e16-4338-11e5-842c-c4c65e3a934e.png)

i try to make dark skin

**Comment by onukore** [comment] 2015-08-15 09:16
i want to buy radium for year in one time, i don't have paypal account and don't want it , i just want to pay you like in renoise registering , you did it ?

**Comment by kmatheussen** [comment] 2015-08-15 10:14
Please mail me privately, and I'll send you my iban number and swift code.

**Comment by kmatheussen** [comment] 2015-08-15 10:16
> I try to make dark skin
I see that. It shouldn't be much work to add custom colors which you can edit manually in the HOME/.radium/colors text file. I'll see if I can fix it soon. In the longer term, a better color configuration GUI should be made as well.

**Comment by kmatheussen** [comment] 2015-08-15 10:17
Nice colors by the way. Especially the waveform.

**Comment by kmatheussen** [comment] 2015-08-15 10:22
> Please mail me privately, and I'll send you my iban number and swift code.

You can also donate 24 EUR for a one year subscription, using the "donate" button in the front page of the radium home page. You don't need a paypal account to pay with paypal if you have a credit card. Just write that in the comment that you want to subscribe for one year, payed in advance, and I'll create an account manually as soon as possible.

**Comment by onukore** [comment] 2015-08-15 10:33
ok , I will do that  very soon

**Comment by onukore** [comment] 2015-08-15 13:59
dontion done , I 'm in a hurry to have the full version

**Comment by onukore** [comment] 2015-08-15 18:30
re hi
one more thing , the gradation in the slider and sample waves are not very useful , simplicity is best , keep it for the meter

it's last for today :)
sorry

**Comment by kmatheussen** [comment] 2015-08-17 10:43
I agree that gradients for the sliders aren't very useful, but the gradients for the waveforms have function. First of all, there are only gradients if there are pitch changes (portamento). A horizontal gradient is turned on if there is a portamento effect, while the vertical gradient actually shows the pitch.

**Comment by onukore** [comment] 2015-08-17 12:40
Ok i see you're right

**Comment by kmatheussen** [comment] 2015-08-22 17:30
I've improved the color configuration GUI now (it's in the preferences dialog now), and moved away from the fixed 16 numbers of colors, although a lot of things are still shared. The reason for this number (16) is simply that radium was once created for a computer type that only was able to support 16 different colors, without being very slow (radium is an old program). But with the latest change, it's relatively simple to gradually move away from this limitation. I've also added separate colors for the sliders. Hope to release a new version tomorrow.

**Comment by onukore** [comment] 2015-08-23 08:20
hi ,
nice to hear, my dark skin will be better, an other think, link machine is too dark for this skin, is possible to have color change for this ?

**Comment by kmatheussen** [comment] 2015-08-23 08:39
You mean the color of the connections between objects in the mixer? Yes, I can fix that easily. Just list up things you need to configure.

**Comment by onukore** [comment] 2015-08-23 09:19
1-middle bar in edit mode is same than note in piano roll and line separate note and graphic in track 
2-sample background  same than pan and volume actived in track header
3-button colors et texte colors are fixed
4-obects texte and contour
5-object colors back text name, why we have lot off colors, i think 1 color generator, 1 for effect and 1 for meta (master, bus,midi message,patchbay, utiles ect..) if is possible

**Comment by kmatheussen** [comment] 2015-08-23 10:26
Didn't have time to fix for this release. BTW, please create new issues for new topics.

**Comment by kmatheussen** [comment] 2015-08-23 10:27
Moved here: https://github.com/kmatheussen/radium/issues/350

**Closed by kmatheussen** 2015-08-23 10:27 UTC
